/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-conventions")
    id("io.papermc.paperweight.userdev") version "2.0.0-beta.18" apply false
    id("com.gradleup.shadow") version "9.0.1" apply false
    kotlin("jvm")
}


dependencies {
    implementation(kotlin("stdlib-jdk8"))

}
repositories {
    mavenCentral()
}
kotlin {
    jvmToolchain(8)
}