pluginManagement {
    plugins {
        kotlin("jvm") version "2.1.21"
    }
}
plugins {
    id("org.gradle.toolchains.foojay-resolver-convention") version "0.8.0"
}
/*
 * This file was generated by the Gradle 'init' task.
 */

rootProject.name = "movecraft-space-parent"
include(":LandsExpansion")
include(":FactionsExpansion")
include(":TownyExpansion")
include(":GriefPreventionExpansion")
include(":AsteroidBeltExpansion")
include(":movecraft-space-api")
include(":FactionsBlueExpansion")
include(":WorldGuardExpansion")
include(":RedProtectExpansion")
include(":DynmapExpansion")
include(":FactionsUUIDExpansion")
include(":HyperspaceExpansion")
include(":WorldBorderExpansion")
include(":Movecraft-Space")
project(":LandsExpansion").projectDir = file("expansions/LandsExpansion")
project(":FactionsExpansion").projectDir = file("expansions/FactionsExpansion")
project(":TownyExpansion").projectDir = file("expansions/TownyExpansion")
project(":GriefPreventionExpansion").projectDir = file("expansions/GriefPreventionExpansion")
project(":AsteroidBeltExpansion").projectDir = file("expansions/AsteroidBeltExpansion")
project(":movecraft-space-api").projectDir = file("api")
project(":FactionsBlueExpansion").projectDir = file("expansions/FactionsBlueExpansion")
project(":WorldGuardExpansion").projectDir = file("expansions/WorldGuardExpansion")
project(":RedProtectExpansion").projectDir = file("expansions/RedProtectExpansion")
project(":DynmapExpansion").projectDir = file("expansions/DynmapExpansion")
project(":FactionsUUIDExpansion").projectDir = file("expansions/FactionsUUIDExpansion")
project(":HyperspaceExpansion").projectDir = file("expansions/HyperspaceExpansion")
project(":WorldBorderExpansion").projectDir = file("expansions/WorldBorderExpansion")
project(":Movecraft-Space").projectDir = file("plugin")
