/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    `java-library`
    `maven-publish`
}

repositories {
    mavenLocal()

    maven {
        url = uri("http://repo.mikeprimm.com/")
        isAllowInsecureProtocol = true
    }

    maven {
        url = uri("https://repo.mikeprimm.com")
    }

    maven {
        url = uri("https://maven.enginehub.org/repo/")
    }

    maven {
        url = uri("https://raw.githubusercontent.com/FabioZumbi12/RedProtect/mvn-repo/")
    }

    maven {
        url = uri("https://jitpack.io")
    }
    maven("https://repo.papermc.io/repository/maven-public/")

}

dependencies {
    api("org.jetbrains.kotlin:kotlin-stdlib:1.5.21")
    testImplementation("org.jetbrains.kotlin:kotlin-test-junit:1.5.21")
    testImplementation("junit:junit:4.12")
}

group = "io.github.eirikh1996"
version = "2.0"

java.sourceCompatibility = JavaVersion.VERSION_23

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}

tasks.withType<Javadoc>() {
    options.encoding = "UTF-8"
}
