/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-conventions")
    kotlin("jvm")
    id("io.github.0ffz.github-packages") version "1.2.1"
}

java.toolchain.languageVersion = JavaLanguageVersion.of(21)

dependencies {
    compileOnly("org.jetbrains.kotlin:kotlin-stdlib:1.6.0")
    compileOnly("org.jetbrains.kotlin:kotlin-test-junit:1.6.0")
    implementation("net.kyori:adventure-text-serializer-plain:4.24.0")
    api(libs.io.papermc.paper.paper.api)
    api("net.countercraft:movecraft:+")
}

description = "Movecraft-Space-API"
repositories {
    mavenCentral()
    maven { githubPackage("apdevteam/movecraft")(this) }
}

java {
    sourceCompatibility = JavaVersion.VERSION_21
    targetCompatibility = JavaVersion.VERSION_21
}

kotlin {
    jvmToolchain(21)
}